### ISSUE TITLE
Populate the database with example data fail

### ISSUE THREAD

**Issue by camux** [mirumee/saleor-platform#23]
Running next command fail:

sudo docker-compose run --rm web python3 manage.py populatedb --createsuperuser

Starting saleor-platform_db_1     ... done
Starting saleor-platform_jaeger_1 ... done
Starting saleor-platform_redis_1  ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "shipping_shippingzone" does not exist
LINE 1: ...ountries", "shipping_shippingzone"."default" FROM "shipping_...
                                                             ^

...
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "shipping_shippingzone" does not exist
LINE 1: ...ountries", "shipping_shippingzone"."default" FROM "shipping_...

**Comment by NyanKiyoshi** [comment]
Try first running:
```
sudo docker-compose run --rm web python3 manage.py migrate
```

Then `populatedb` again
