### ISSUE TITLE
🐛BUG: Storefront and dashboard both broken

### ISSUE THREAD

**Issue by kilinkis** [mirumee/saleor-platform#36]
I ran all the steps as explained in the readme (I did this before in previous versions with no problem).

But now, after running `docker-compose up` the landing page in port 8000 shows the links to the apps, but Storefront and Dashboard are both broken.

In the terminal I see several errors like:

```
storefront_1  | ERROR in useCheckoutStepState.ts
storefront_1  | ./src/@next/hooks/useCheckoutStepState.ts
storefront_1  | [tsl] ERROR in useCheckoutStepState.ts(16,5)
storefront_1  |       TS1005: ':' expected.
storefront_1  |  @ ./src/@next/hooks/index.ts 13:9-42
storefront_1  |  @ ./src/@next/components/atoms/DropdownMenu/DropdownMenu.tsx
storefront_1  |  @ ./src/@next/components/atoms/DropdownMenu/index.ts
storefront_1  |  @ ./src/@next/components/atoms/index.ts
storefront_1  |  @ ./src/index.tsx
storefront_1  |  @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 (webpack)/hot/only-dev-server.js ./src/index.tsx
```

and

```
storefront_1  | TS2305: Module '"../../../../node_modules/@types/react-router-dom"' has no exported member 'useLocation'.
storefront_1  | ERROR in /app/src/@sdk/network/index.ts(338,9):
storefront_1  | TS2322: Type '{ checkoutInput: { billingAddress: { city: string; companyName: string; country: string; countryArea: string; firstName: string; lastName: string; phone: string; postalCode: string; streetAddress1: string; streetAddress2: string; }; email: string; lines: { ...; }[]; shippingAddress: { ...; }; }; }' is not assignable to type 'CreateCheckoutVariables'.
storefront_1  |   Types of property 'checkoutInput' are incompatible.
storefront_1  |     Type '{ billingAddress: { city: string; companyName: string; country: string; countryArea: string; firstName: string; lastName: string; phone: string; postalCode: string; streetAddress1: string; streetAddress2: string; }; email: string; lines: { ...; }[]; shippingAddress: { ...; }; }' is not assignable to type 'CheckoutCreateInput'.
```

and in the terminal (browser) I see several errors like: (for storefront)
```
useCheckoutStepFromPath.ts:27 Uncaught Error: Module parse failed: Unexpected token (7:54)
You may need an appropriate loader to handle this file type.
| exports.useCheckoutStepState = (items, checkout, payment) => {
|     const isShippingRequiredForProducts = items &&
>         items.some(({ variant }) => variant.product ? .productType.isShippingRequired
|             :
|         );
react_devtools_backend.js:6 ./src/@next/components/organisms/StripeCreditCardForm/StripeCreditCardForm.tsx
Module not found: Error: Can't resolve '@stripe/react-stripe-js' in '/app/src/@next/components/organisms/StripeCreditCardForm'
react_devtools_backend.js:6 CartSummary.tsx
./src/@next/components/organisms/CartSummary/CartSummary.tsx
[tsl] ERROR in CartSummary.tsx(76,13)
      TS1005: ':' expected.
r @ react_devtools_backend.js:6
errors @ client:168
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
react_devtools_backend.js:6 CheckoutAddress.tsx
./src/@next/components/organisms/CheckoutAddress/CheckoutAddress.tsx
[tsl] ERROR in CheckoutAddress.tsx(36,39)
      TS1109: Expression expected.
```

and in the terminal (for backend) I see these errors:

```
index.tsx:1 Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-proposal-optional-chaining' from '/app'
    at Function.module.exports [as sync] (:9000/app/node_modules/resolve/lib/sync.js:74)
    at resolveStandardizedName (:9000/app/node_modules/@babel/core/lib/config/files/plugins.js:101)
    at resolvePlugin (:9000/app/node_modules/@babel/core/lib/config/files/plugins.js:54)
    at loadPlugin (:9000/app/node_modules/@babel/core/lib/config/files/plugins.js:62)
    at createDescriptor (:9000/app/node_modules/@babel/core/lib/config/config-descriptors.js:154)
    at items.map (:9000/app/node_modules/@babel/core/lib/config/config-descriptors.js:109)
    at Array.map (<anonymous>)
    at createDescriptors (:9000/app/node_modules/@babel/core/lib/config/config-descriptors.js:109)
    at createPluginDescriptors (:9000/app/node_modules/@babel/core/lib/config/config-descriptors.js:105)
    at plugins (:9000/app/node_modules/@babel/core/lib/config/config-descriptors.js:40)
    at eval (index.tsx:1)
    at Object../src/index.tsx (dashboard.js?8fc242e5fa5506fef701:1188)
    at __webpack_require__ (dashboard.js?8fc242e5fa5506fef701:727)
    at fn (dashboard.js?8fc242e5fa5506fef701:101)
    at Object.0 (dashboard.js?8fc242e5fa5506fef701:1201)
    at __webpack_require__ (dashboard.js?8fc242e5fa5506fef701:727)
    at dashboard.js?8fc242e5fa5506fef701:794
    at dashboard.js?8fc242e5fa5506fef701:797
eval @ index.tsx:1
./src/index.tsx @ dashboard.js?8fc242e5fa5506fef701:1188
__webpack_require__ @ dashboard.js?8fc242e5fa5506fef701:727
fn @ dashboard.js?8fc242e5fa5506fef701:101
0 @ dashboard.js?8fc242e5fa5506fef701:1201
__webpack_require__ @ dashboard.js?8fc242e5fa5506fef701:727
(anonymous) @ dashboard.js?8fc242e5fa5506fef701:794
(anonymous) @ dashboard.js?8fc242e5fa5506fef701:797
client?8a49:48 [WDS] Hot Module Replacement enabled.
client?8a49:52 [WDS] Live Reloading enabled.
client?8a49:150 [WDS] Errors while compiling. Reload prevented.
errors @ client?8a49:150
eval @ socket.js?e29c:47
sock.onmessage @ SockJSClient.js?0a33:63
EventTarget.dispatchEvent @ sockjs.js?9be2:170
eval @ sockjs.js?9be2:888
SockJS._transportMessage @ sockjs.js?9be2:886
EventEmitter.emit @ sockjs.js?9be2:86
WebSocketTransport.ws.onmessage @ sockjs.js?9be2:2962
client?8a49:159 ./src/index.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-proposal-optional-chaining' from '/app'
    at Function.module.exports [as sync] (/app/node_modules/resolve/lib/sync.js:74:15)
    at resolveStandardizedName (/app/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/app/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/app/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/app/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/app/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/app/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/app/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/app/node_modules/@babel/core/lib/config/config-descriptors.js:40:19)
errors @ client?8a49:159
eval @ socket.js?e29c:47
sock.onmessage @ SockJSClient.js?0a33:63
EventTarget.dispatchEvent @ sockjs.js?9be2:170
eval @ sockjs.js?9be2:888
SockJS._transportMessage @ sockjs.js?9be2:886
EventEmitter.emit @ sockjs.js?9be2:86
WebSocketTransport.ws.onmessage @ sockjs.js?9be2:2962
favicon.ico:1 GET http://localhost:9000/favicon.ico 404 (Not Found)
```

**Comment by maarcingebala** [comment]
Hey @kilinkis, most likely this is a local problem with Docker that failed to update/rebuild containers. We added instructions in the README how to rebuild the containers and fix such issues: https://github.com/mirumee/saleor-platform#how-to-solve-issues-with-lack-of-available-space-or-build-errors-after-update

Let me know if this helps.

**Comment by kilinkis** [comment]
ah! nice catch @maarcingebala! thanks, that did the trick :) 

for other people with the same issue, I think when this failed I had less than 10gb free in my disk.
