### ISSUE TITLE
The home page works, but there are 404 on the others.

### ISSUE THREAD

**Issue by maltitco** [mirumee/saleor-platform#59]
I have error 404 when trying to go to subpages.
In the docker console I have:

`api_1         | INFO django.server "OPTIONS /graphql/ HTTP/1.1" 200 0 [PID:9:Thread-3]
api_1         | INFO django.server "OPTIONS /graphql/ HTTP/1.1" 200 0 [PID:9:Thread-3]
api_1         | INFO django.server "OPTIONS /graphql/ HTTP/1.1" 200 0 [PID:9:Thread-3]
api_1         | ERROR graphql.execution.executor An error occurred while resolving field Query.shop [PID:9:Thread-3]
api_1         | Traceback (most recent call last):
api_1         |   File "/usr/local/lib/python3.8/site-packages/graphql_jwt/utils.py", line 86, in get_payload
api_1         |     payload = jwt_settings.JWT_DECODE_HANDLER(token, context)
api_1         |   File "/usr/local/lib/python3.8/site-packages/graphql_jwt/utils.py", line 45, in jwt_decode
api_1         |     return jwt.decode(
api_1         |   File "/usr/local/lib/python3.8/site-packages/jwt/api_jwt.py", line 91, in decode
api_1         |     decoded = super(PyJWT, self).decode(
api_1         |   File "/usr/local/lib/python3.8/site-packages/jwt/api_jws.py", line 155, in decode
api_1         |     self._verify_signature(payload, signing_input, header, signature,
api_1         |   File "/usr/local/lib/python3.8/site-packages/jwt/api_jws.py", line 223, in _verify_signature
api_1         |     raise InvalidSignatureError('Signature verification failed')
api_1         | jwt.exceptions.InvalidSignatureError: Signature verification failed`

**Comment by maltitco** [comment]
Clearing the browser cache will solve the problem.
