### ISSUE TITLE
Error: Cannot find module 'phantomjs-prebuilt'

### ISSUE THREAD

**Issue by michalpulpan** [mirumee/saleor-platform#98]
Hello,

I'm trying to setup `saleor-platform` on my local dev machine. Sadly I'm getting error related to `phantomjs-prebuilt` in `storefront_1` container.
I'm running Docker Desktop 3.3.2, Docker Engine 20.10.6 on M1 (Apple Silicon) Macbook Pro (but that shouldn't cause the issue...)

By following all of the steps from docs:
```
git clone https://github.com/mirumee/saleor-platform.git --recursive --jobs 3
cd saleor-platform
docker-compose build
docker-compose run --rm api python3 manage.py migrate
docker-compose run --rm api python3 manage.py collectstatic --noinput
docker-compose run --rm api python3 manage.py populatedb
docker-compose run --rm api python3 manage.py createsuperuser
docker-compose up
```

My error is:
```
storefront_1  | Using 1 worker with 2048MB memory limit
storefront_1  | ℹ ｢wds｣: Project is running at http://localhost:3000/
storefront_1  | ℹ ｢wds｣: webpack output is served from /
storefront_1  | ℹ ｢wds｣: Content not from webpack is served from /app
storefront_1  | ℹ ｢wds｣: 404s will fallback to /index.html
storefront_1  | ✖ ｢wdm｣: Error: Cannot find module 'phantomjs-prebuilt'
storefront_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
storefront_1  |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
storefront_1  |     at Module.require (internal/modules/cjs/loader.js:692:17)
storefront_1  |     at require (internal/modules/cjs/helpers.js:25:18)
storefront_1  |     at Object.<anonymous> (/app/node_modules/svg2png/lib/svg2png.js:6:22)
storefront_1  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
storefront_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
storefront_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
storefront_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
storefront_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
storefront_1  | Browserslist: caniuse-lite is outdated. Please run next command `npm update`
```

I already tried several ways how to install `phantomjs-prebuilt`, but nothing worked. Adding `RUN npm install phantomjs-prebuilt@2.1.16 --ignore-scripts` into my `saleor-storefront/Dockerfile.dev` did not help, neither `RUN npm install -g phantomjs-prebuilt --phantomjs_cdnurl=https://bitbucket.org/ariya/phantomjs/downloads --ignore-scripts` or adding `phantomjs-prebuilt` into `package.json`.

Has anyone faced this issue? I'm pretty new to NodeJS as well as NPM errors.

Thanks.

**Comment by michalpulpan** [comment]
Okay, I Think this got resolved by setting higher version of NODE package in Dockerfile.dev.
